cdef extern from "qdmi/constants.h":

    cdef enum QDMI_STATUS:
        QDMI_WARN_GENERAL = 1
        QDMI_SUCCESS = 0
        QDMI_ERROR_FATAL = -1
        QDMI_ERROR_OUTOFMEM = -2
        QDMI_ERROR_NOTIMPLEMENTED = -3
        QDMI_ERROR_LIBNOTFOUND = -4
        QDMI_ERROR_NOTFOUND = -5
        QDMI_ERROR_OUTOFRANGE = -6
        QDMI_ERROR_INVALIDARGUMENT = -7
        QDMI_ERROR_PERMISSIONDENIED = -8
        QDMI_ERROR_NOTSUPPORTED = -9
        QDMI_ERROR_BADSTATE = -10
        QDMI_ERROR_TIMEOUT = -11


    cdef enum QDMI_DEVICE_SESSION_PARAMETER_T:
        QDMI_DEVICE_SESSION_PARAMETER_BASEURL = 0
        QDMI_DEVICE_SESSION_PARAMETER_TOKEN = 1
        QDMI_DEVICE_SESSION_PARAMETER_AUTHFILE = 2
        QDMI_DEVICE_SESSION_PARAMETER_AUTHURL = 3
        QDMI_DEVICE_SESSION_PARAMETER_USERNAME = 4
        QDMI_DEVICE_SESSION_PARAMETER_PASSWORD = 5
        QDMI_DEVICE_SESSION_PARAMETER_MAX = 6
        QDMI_DEVICE_SESSION_PARAMETER_CUSTOM1 = 999999995
        QDMI_DEVICE_SESSION_PARAMETER_CUSTOM2 = 999999996
        QDMI_DEVICE_SESSION_PARAMETER_CUSTOM3 = 999999997
        QDMI_DEVICE_SESSION_PARAMETER_CUSTOM4 = 999999998
        QDMI_DEVICE_SESSION_PARAMETER_CUSTOM5 = 999999999

    ctypedef QDMI_DEVICE_SESSION_PARAMETER_T QDMI_Device_Session_Parameter


    enum QDMI_DEVICE_JOB_PROPERTY_T:
        QDMI_DEVICE_JOB_PROPERTY_ID = 0
        QDMI_DEVICE_JOB_PROPERTY_PROGRAMFORMAT = 1
        QDMI_DEVICE_JOB_PROPERTY_PROGRAM = 2
        QDMI_DEVICE_JOB_PROPERTY_SHOTSNUM = 3
        QDMI_DEVICE_JOB_PROPERTY_MAX = 4
        QDMI_DEVICE_JOB_PROPERTY_CUSTOM1 = 999999995
        QDMI_DEVICE_JOB_PROPERTY_CUSTOM2 = 999999996
        QDMI_DEVICE_JOB_PROPERTY_CUSTOM3 = 999999997
        QDMI_DEVICE_JOB_PROPERTY_CUSTOM4 = 999999998
        QDMI_DEVICE_JOB_PROPERTY_CUSTOM5 = 999999999

    ctypedef QDMI_DEVICE_JOB_PROPERTY_T QDMI_Device_Job_Property


    cdef enum QDMI_DEVICE_JOB_PARAMETER_T:
        QDMI_DEVICE_JOB_PARAMETER_PROGRAMFORMAT = 0
        QDMI_DEVICE_JOB_PARAMETER_PROGRAM = 1
        QDMI_DEVICE_JOB_PARAMETER_SHOTSNUM = 2
        QDMI_DEVICE_JOB_PARAMETER_MAX = 3
        QDMI_DEVICE_JOB_PARAMETER_CUSTOM1 = 999999995
        QDMI_DEVICE_JOB_PARAMETER_CUSTOM2 = 999999996
        QDMI_DEVICE_JOB_PARAMETER_CUSTOM3 = 999999997
        QDMI_DEVICE_JOB_PARAMETER_CUSTOM4 = 999999998
        QDMI_DEVICE_JOB_PARAMETER_CUSTOM5 = 999999999

    ctypedef QDMI_DEVICE_JOB_PARAMETER_T QDMI_Device_Job_Parameter


    enum QDMI_DEVICE_PROPERTY_T:
        QDMI_DEVICE_PROPERTY_NAME = 0
        QDMI_DEVICE_PROPERTY_VERSION = 1
        QDMI_DEVICE_PROPERTY_STATUS = 2
        QDMI_DEVICE_PROPERTY_LIBRARYVERSION = 3
        QDMI_DEVICE_PROPERTY_QUBITSNUM = 4
        QDMI_DEVICE_PROPERTY_SITES = 5
        QDMI_DEVICE_PROPERTY_OPERATIONS = 6
        QDMI_DEVICE_PROPERTY_COUPLINGMAP = 7
        QDMI_DEVICE_PROPERTY_NEEDSCALIBRATION = 8
        QDMI_DEVICE_PROPERTY_PULSESUPPORT = 9
        QDMI_DEVICE_PROPERTY_LENGTHUNIT = 10
        QDMI_DEVICE_PROPERTY_LENGTHSCALEFACTOR = 11
        QDMI_DEVICE_PROPERTY_DURATIONUNIT = 12
        QDMI_DEVICE_PROPERTY_DURATIONSCALEFACTOR = 13
        QDMI_DEVICE_PROPERTY_MINATOMDISTANCE = 14
        QDMI_DEVICE_PROPERTY_TELEMETRYSENSORS = 15
        QDMI_DEVICE_PROPERTY_MAX = 16
        QDMI_DEVICE_PROPERTY_CUSTOM1 = 999999995
        QDMI_DEVICE_PROPERTY_CUSTOM2 = 999999996
        QDMI_DEVICE_PROPERTY_CUSTOM3 = 999999997
        QDMI_DEVICE_PROPERTY_CUSTOM4 = 999999998
        QDMI_DEVICE_PROPERTY_CUSTOM5 = 999999999

    ctypedef QDMI_DEVICE_PROPERTY_T QDMI_Device_Property


    enum QDMI_SITE_PROPERTY_T:
        QDMI_SITE_PROPERTY_INDEX = 0
        QDMI_SITE_PROPERTY_T1 = 1
        QDMI_SITE_PROPERTY_T2 = 2
        QDMI_SITE_PROPERTY_NAME = 3
        QDMI_SITE_PROPERTY_XCOORDINATE = 4
        QDMI_SITE_PROPERTY_YCOORDINATE = 5
        QDMI_SITE_PROPERTY_ZCOORDINATE = 6
        QDMI_SITE_PROPERTY_ISZONE = 7
        QDMI_SITE_PROPERTY_XEXTENT = 8
        QDMI_SITE_PROPERTY_YEXTENT = 9
        QDMI_SITE_PROPERTY_ZEXTENT = 10
        QDMI_SITE_PROPERTY_MODULEINDEX = 11
        QDMI_SITE_PROPERTY_SUBMODULEINDEX = 12
        QDMI_SITE_PROPERTY_MAX = 13
        QDMI_SITE_PROPERTY_CUSTOM1 = 999999995
        QDMI_SITE_PROPERTY_CUSTOM2 = 999999996
        QDMI_SITE_PROPERTY_CUSTOM3 = 999999997
        QDMI_SITE_PROPERTY_CUSTOM4 = 999999998
        QDMI_SITE_PROPERTY_CUSTOM5 = 999999999

    ctypedef QDMI_SITE_PROPERTY_T QDMI_Site_Property


    enum QDMI_OPERATION_PROPERTY_T:
        QDMI_OPERATION_PROPERTY_NAME = 0
        QDMI_OPERATION_PROPERTY_QUBITSNUM = 1
        QDMI_OPERATION_PROPERTY_PARAMETERSNUM = 2
        QDMI_OPERATION_PROPERTY_DURATION = 3
        QDMI_OPERATION_PROPERTY_FIDELITY = 4
        QDMI_OPERATION_PROPERTY_INTERACTIONRADIUS = 5
        QDMI_OPERATION_PROPERTY_BLOCKINGRADIUS = 6
        QDMI_OPERATION_PROPERTY_IDLINGFIDELITY = 7
        QDMI_OPERATION_PROPERTY_ISZONED = 8
        QDMI_OPERATION_PROPERTY_SITES = 9
        QDMI_OPERATION_PROPERTY_MEANSHUTTLINGSPEED = 10
        QDMI_OPERATION_PROPERTY_MAX = 11
        QDMI_OPERATION_PROPERTY_CUSTOM1 = 999999995
        QDMI_OPERATION_PROPERTY_CUSTOM2 = 999999996
        QDMI_OPERATION_PROPERTY_CUSTOM3 = 999999997
        QDMI_OPERATION_PROPERTY_CUSTOM4 = 999999998
        QDMI_OPERATION_PROPERTY_CUSTOM5 = 999999999

    ctypedef QDMI_OPERATION_PROPERTY_T QDMI_Operation_Property


    enum QDMI_JOB_STATUS_T:
        QDMI_JOB_STATUS_CREATED = 0
        QDMI_JOB_STATUS_SUBMITTED = 1
        QDMI_JOB_STATUS_QUEUED = 2
        QDMI_JOB_STATUS_RUNNING = 3
        QDMI_JOB_STATUS_DONE = 4
        QDMI_JOB_STATUS_CANCELED = 5
        QDMI_JOB_STATUS_FAILED = 6

    ctypedef QDMI_JOB_STATUS_T QDMI_Job_Status


    enum QDMI_JOB_RESULT_T:
        QDMI_JOB_RESULT_SHOTS = 0
        QDMI_JOB_RESULT_HIST_KEYS = 1
        QDMI_JOB_RESULT_HIST_VALUES = 2
        QDMI_JOB_RESULT_STATEVECTOR_DENSE = 3
        QDMI_JOB_RESULT_PROBABILITIES_DENSE = 4
        QDMI_JOB_RESULT_STATEVECTOR_SPARSE_KEYS = 5
        QDMI_JOB_RESULT_STATEVECTOR_SPARSE_VALUES = 6
        QDMI_JOB_RESULT_PROBABILITIES_SPARSE_KEYS = 7
        QDMI_JOB_RESULT_PROBABILITIES_SPARSE_VALUES = 8
        QDMI_JOB_RESULT_MAX = 9
        QDMI_JOB_RESULT_CUSTOM1 = 999999995
        QDMI_JOB_RESULT_CUSTOM2 = 999999996
        QDMI_JOB_RESULT_CUSTOM3 = 999999997
        QDMI_JOB_RESULT_CUSTOM4 = 999999998
        QDMI_JOB_RESULT_CUSTOM5 = 999999999

    ctypedef QDMI_JOB_RESULT_T QDMI_Job_Result
